# Generated by Django 4.1 on 2023-07-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfomodel',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
    ]
