# Generated by Django 4.1 on 2023-07-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_alter_contactmodel_email_alter_userinfomodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='message',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
