# Generated by Django 4.1 on 2023-07-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_alter_contactmodel_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='email',
            field=models.CharField(default='example@example.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='userinfomodel',
            name='aadhar',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userinfomodel',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userinfomodel',
            name='parent_referral_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userinfomodel',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userinfomodel',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userinfomodel',
            name='user_referral_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userinfomodel',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
