# Generated by Django 4.1 on 2023-07-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_alter_contactmodel_email_alter_userinfomodel_aadhar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
