# Generated by Django 4.1 on 2023-07-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_alter_contactmodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfomodel',
            name='answer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userinfomodel',
            name='secret_question',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
